### ISSUE TITLE
how to get nerfw_split.csv?

### ISSUE THREAD

**Issue by wzh506** [jkulhanek/wild-gaussians#12]
I have dataset trevi_fountain,like 
_**- dense
        --images
        --images_2
        --sparse
        --stereo
-trevi.tsv**_
,but I don't find how and where to get nerfw_split.csv which is code needed . could someone help me?

**Comment by jkulhanek** [comment]
Hi, you can just use `nerfbaselines download-dataset phototourism/trevi-fountain` and all required data shall be downloaded automatically. Btw, the nerfw_split.csv is your trevi.tsv file.

**Comment by wzh506** [comment]
Thank you!

**Comment by GopiRajuMatta** [comment]
For custom dataset how to get this nerfw_split.csv?
