### ISSUE TITLE
how to tackle the wild-gaussians method?

### ISSUE THREAD

**Issue by kalelpark** [jkulhanek/wild-gaussians#15]
Hi, thank you for sharing such a great work.

I want to edit the method part of the code, but rely on the nerfbaselines library, 
so could you give me some guidelines on how to take away from dependency?

Thanks a lot.

**Comment by jkulhanek** [comment]
Hi, thank you for the interest. Nerfbaselines is optional depencency. It is not needed to train/use the model. Feel free to modify the code without using nerfbaselines!
