### ISSUE TITLE
How to prepare/pre-process other datasets?

### ISSUE THREAD

**Issue by GeoVectorMatrix** [jkulhanek/wild-gaussians#17]
Great job!

Is there a tutorial available for preparing other datasets to fit wild-gaussians? For instance, other scenes  in Nerf-on-the-go.

**Comment by jkulhanek** [comment]
Hi,

Sorry, there is no tutorial, however, there are no special steps needed. `wild-gaussians` should be able to load any COLMAP dataset. In case of NeRF on-the-go, do you have the original sparse/ directory with the COLMAP reconstruction? If yes, just point `wild-gaussians` to the path containing the dataset. If you have a dataset with just poses (no 3D points), you can use COLMAP to triangulate the points to obtain the sparse reconstruction. Take a look at colmap documentation.

Was this helpful or do you need further guidance? I guess I can extend the readme with some section on how to do it.

**Comment by GeoVectorMatrix** [comment]
Thank you for your response. Since there are no special processes involved, I will try using COLMAP to obtain the "sparse" -related folder. Great work, and I look forward to more interesting discoveries.
