### ISSUE TITLE
Improve discoverability on Hugging Face, make sure download stats work

### ISSUE THREAD

**Issue by NielsRogge** [jkulhanek/wild-gaussians#2]
Hi,

Congrats on this work! Niels here from the open-source team at Hugging Face. It's great to see you're releasing models on HF :) I see they are currently not linked to the paper page: https://huggingface.co/papers/2407.08447, would you be able to link them?

Here's a guide on that: https://huggingface.co/docs/hub/en/model-cards#linking-a-paper.

I also see that currently download stats aren't working for your models. This is due to the model repository containing various checkpoints, which do not contain a config.json file. See here for more info: https://huggingface.co/docs/hub/models-download-stats. Usually we recommend to push checkpoints each to a single repository.

I see that the zip files contain a config.yaml file which could make downloads work if the folder just gets uploaded without using zip.

However, we also offer a few other options to make them work:

1) either we can open a PR on the huggingface.js repository to view "wild-gaussians" as a library, for which we add dedicated support. See this PR as an example: https://github.com/huggingface/huggingface.js/pull/784
2) one could leverage the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/en/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) to push model checkpoints to separate model repositories, each containing a config.json and safetensors file (which is considered safer than pickle).

Let me know if you need any help!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by jkulhanek** [comment]
Hi Niels,

Thank you very much!
I will link the paper.

Regarding the download stats. I think option 1 is preferable as creating a repo for each scene would be a bit overkill I think.

Best,
Jonas

**Comment by jkulhanek** [comment]
The checkpoints should now be linked correctly.
