### ISSUE TITLE
About Training

### ISSUE THREAD

**Issue by BruceRull** [jkulhanek/wild-gaussians#24]
Thank you for your excellent work, I've been troubled by dataset types lately. I tried many methods, but they all loaded the default type. Please tell me how to solve it.
![24d03663f25d2d4a2e1facb8f3898271](https://github.com/user-attachments/assets/15642dc3-750c-4535-90d9-aaf3619416ef)

**Comment by BruceRull** [comment]
Thank you for your timely reply, I am using the nerfbaselines train command.
![b1a7050ba121a990892f937553a835c8](https://github.com/user-attachments/assets/dde16218-af93-45ff-a597-39110c03612b)
The data set is the original data set of nerfw. How can I get the nb-info.json file?
![64aba671f54cfaefaf88d553cab00a3a](https://github.com/user-attachments/assets/5a6845fa-4fa7-4485-8230-43736df3c6b6)

**Comment by jkulhanek** [comment]
Can you please try running: `nerfbaselines train --method wild-gaussians --data external://phototourism/brandenburg-gate` if that resolves the issue?

**Comment by BruceRull** [comment]
OK， I understand.
