### ISSUE TITLE
Baselines appear broken

### ISSUE THREAD

**Issue by Joaquin-Gajardo** [jkulhanek/wild-gaussians#26]
Hi @jkulhanek , thanks a lot for this amazing work!

I can successfully run wild-gaussians as in the examples in the readme, but can't run any other baseline. For example for both, `gaussian-splatting` and `scaffold-gs`, I'm hitting the error below. It seems something is broken for me with the current installation instructions,  are you able to reproduce on your end?

Thanks!

````
(wildgaussians) (gs) root@acd509ff003d:/workspace/wild-gaussians# nerfbaselines train --method gaussian-splatting---data external://phototourism/sacre-coeur
info: Using method: gaussian-splatting, backend: python
Traceback (most recent call last):
  File "/opt/conda/envs/wildgaussians/bin/nerfbaselines", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/wildgaussians/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/wildgaussians/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/wildgaussians/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/wildgaussians/lib/python3.11/site-packages/nerfbaselines/cli/_common.py", line 499, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/wildgaussians/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/wildgaussians/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/wildgaussians/lib/python3.11/site-packages/nerfbaselines/cli/_common.py", line 440, in wrapped
    raise e
  File "/opt/conda/envs/wildgaussians/lib/python3.11/site-packages/nerfbaselines/cli/_common.py", line 433, in wrapped
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/wildgaussians/lib/python3.11/site-packages/nerfbaselines/cli/_train.py", line 97, in train_command
    method_cls = stack.enter_context(build_method_class(method_spec, backend_name))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/wildgaussians/lib/python3.11/contextlib.py", line 517, in enter_context
    result = _enter(cm)
             ^^^^^^^^^^
  File "/opt/conda/envs/wildgaussians/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/opt/conda/envs/wildgaussians/lib/python3.11/site-packages/nerfbaselines/_method_utils.py", line 89, in build_method_class
    yield cast(Type[Method], backend_impl.static_call(f"{build_method.__module__}:{build_method.__name__}", spec))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/wildgaussians/lib/python3.11/site-packages/nerfbaselines/backends/_common.py", line 225, in static_call
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/wildgaussians/lib/python3.11/site-packages/nerfbaselines/_method_utils.py", line 66, in _build_method_class_internal
    cls: Any = importlib.import_module(package)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/wildgaussians/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/conda/envs/wildgaussians/lib/python3.11/site-packages/nerfbaselines/methods/gaussian_splatting.py", line 37, in <module>
    from utils.general_utils import PILtoTorch  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'utils'
````

**Comment by jkulhanek** [comment]
Hi, this is likely because you installed “local” installation of wg. That one only supports wildgaussians and nothing else. Hence you use the python backend. Follow the instructions on the nerfbaselines documentation to install nerfbaselines. Basically just create a new conda environment and run pip install nerfbaselines. This will allow you to run not only wild-gaussians, but also all methods integrated into nerfbaselines

**Comment by Joaquin-Gajardo** [comment]
Hi @jkulhanek , thanks for the hint! I got it to work on an HPC, by explicitly adding the conda path to PATH and setup `conda env config vars set NERFBASELINES_BACKEND=conda` before running `pip install nerfbaselines` and training on the other methods. A cache conda environment for each method gets created, but I guess this is expected? By the way, is there a way for setting up the nerfbaselines `cache` folder so it's not at `home`, I don't have much available space there.

Somehow I haven't managed to make it run locally when following the same steps though, it just gets stuck forever at "solving environment" with e.g. `gaussian-splatting`. Below is the output, do you have any idea of what might be going on?

`(nerfbaselines) root@acd509ff003d:/workspace/wild-gaussians# nerfbaselines train --method gaussian-splatting --data external://phototourism/sacre-coeur
info: Using method: gaussian-splatting, backend: conda
Creating new environment /root/.cache/nerfbaselines/conda-envs/gaussian-splatting/af2209beed259f3a45e0aaebd6c540019177739944aaf74ddc7791022ff83d4a/gaussian-splatting
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /root/.cache/nerfbaselines/conda-envs/gaussian-splatting/af2209beed259f3a45e0aaebd6c540019177739944aaf74ddc7791022ff83d4a/gaussian-splatting

  added / updated specs:
    - python=3.9


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge 
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu 
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h4bc722e_7 
  ca-certificates    conda-forge/linux-64::ca-certificates-2024.8.30-hbcca054_0 
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.43-h712a8e2_1 
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5 
  libgcc             conda-forge/linux-64::libgcc-14.1.0-h77fa898_1 
  libgcc-ng          conda-forge/linux-64::libgcc-ng-14.1.0-h69a702a_1 
  libgomp            conda-forge/linux-64::libgomp-14.1.0-h77fa898_1 
  libnsl             conda-forge/linux-64::libnsl-2.0.1-hd590300_0 
  libsqlite          conda-forge/linux-64::libsqlite-3.46.1-hadc24fc_0 
  libuuid            conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0 
  libxcrypt          conda-forge/linux-64::libxcrypt-4.4.36-hd590300_1 
  libzlib            conda-forge/linux-64::libzlib-1.3.1-hb9d3cd8_2 
  ncurses            conda-forge/linux-64::ncurses-6.5-he02047a_1 
  openssl            conda-forge/linux-64::openssl-3.3.2-hb9d3cd8_0 
  pip                conda-forge/noarch::pip-24.2-pyh8b19718_1 
  python             conda-forge/linux-64::python-3.9.20-h13acc7a_1_cpython 
  readline           conda-forge/linux-64::readline-8.2-h8228510_1 
  setuptools         conda-forge/noarch::setuptools-75.1.0-pyhd8ed1ab_0 
  tk                 conda-forge/linux-64::tk-8.6.13-noxft_h4845f30_101 
  tzdata             conda-forge/noarch::tzdata-2024b-hc8b5060_0 
  wheel              conda-forge/noarch::wheel-0.44.0-pyhd8ed1ab_0 
  xz                 conda-forge/linux-64::xz-5.2.6-h166bdaf_0 



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate /root/.cache/nerfbaselines/conda-envs/gaussian-splatting/af2209beed259f3a45e0aaebd6c540019177739944aaf74ddc7791022ff83d4a/gaussian-splatting
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /root/.cache/nerfbaselines/conda-envs/gaussian-splatting/af2209beed259f3a45e0aaebd6c540019177739944aaf74ddc7791022ff83d4a/gaussian-splatting

  added / updated specs:
    - conda-build
    - ffmpeg
    - pip


The following NEW packages will be INSTALLED:

  aom                conda-forge/linux-64::aom-3.9.1-hac33072_0 
  archspec           conda-forge/noarch::archspec-0.2.3-pyhd8ed1ab_0 
  attrs              conda-forge/noarch::attrs-24.2.0-pyh71513ae_0 
  beautifulsoup4     conda-forge/noarch::beautifulsoup4-4.12.3-pyha770c72_0 
  boltons            conda-forge/noarch::boltons-24.0.0-pyhd8ed1ab_0 
  brotli-python      conda-forge/linux-64::brotli-python-1.1.0-py39hf88036b_2 
  c-ares             conda-forge/linux-64::c-ares-1.33.1-heb4867d_0 
  cairo              conda-forge/linux-64::cairo-1.18.0-hebfffa5_3 
  certifi            conda-forge/noarch::certifi-2024.8.30-pyhd8ed1ab_0 
  cffi               conda-forge/linux-64::cffi-1.17.1-py39h15c3d72_0 
  chardet            conda-forge/linux-64::chardet-5.2.0-py39hf3d152e_2 
  charset-normalizer conda-forge/noarch::charset-normalizer-3.3.2-pyhd8ed1ab_0 
  click              conda-forge/noarch::click-8.1.7-unix_pyh707e725_0 
  colorama           conda-forge/noarch::colorama-0.4.6-pyhd8ed1ab_0 
  conda              conda-forge/linux-64::conda-24.9.1-py39hf3d152e_0 
  conda-build        conda-forge/linux-64::conda-build-24.9.0-py39hf3d152e_0 
  conda-index        conda-forge/noarch::conda-index-0.5.0-pyhd8ed1ab_0 
  conda-libmamba-so~ conda-forge/noarch::conda-libmamba-solver-24.9.0-pyhd8ed1ab_0 
  conda-package-han~ conda-forge/noarch::conda-package-handling-2.3.0-pyh7900ff3_0 
  conda-package-str~ conda-forge/noarch::conda-package-streaming-0.10.0-pyhd8ed1ab_0 
  dav1d              conda-forge/linux-64::dav1d-1.2.1-hd590300_0 
  distro             conda-forge/noarch::distro-1.9.0-pyhd8ed1ab_0 
  expat              conda-forge/linux-64::expat-2.6.3-h5888daf_0 
  ffmpeg             conda-forge/linux-64::ffmpeg-7.1.0-gpl_h8657690_700 
  filelock           conda-forge/noarch::filelock-3.16.1-pyhd8ed1ab_0 
  fmt                conda-forge/linux-64::fmt-11.0.2-h434a139_0 
  font-ttf-dejavu-s~ conda-forge/noarch::font-ttf-dejavu-sans-mono-2.37-hab24e00_0 
  font-ttf-inconsol~ conda-forge/noarch::font-ttf-inconsolata-3.000-h77eed37_0 
  font-ttf-source-c~ conda-forge/noarch::font-ttf-source-code-pro-2.038-h77eed37_0 
  font-ttf-ubuntu    conda-forge/noarch::font-ttf-ubuntu-0.83-h77eed37_3 
  fontconfig         conda-forge/linux-64::fontconfig-2.14.2-h14ed4e7_0 
  fonts-conda-ecosy~ conda-forge/noarch::fonts-conda-ecosystem-1-0 
  fonts-conda-forge  conda-forge/noarch::fonts-conda-forge-1-0 
  freetype           conda-forge/linux-64::freetype-2.12.1-h267a509_2 
  fribidi            conda-forge/linux-64::fribidi-1.0.10-h36c2ea0_0 
  frozendict         conda-forge/linux-64::frozendict-2.4.4-py39h8cd3c5a_1 
  gmp                conda-forge/linux-64::gmp-6.3.0-hac33072_2 
  graphite2          conda-forge/linux-64::graphite2-1.3.13-h59595ed_1003 
  h2                 conda-forge/linux-64::h2-4.1.0-py39hf3d152e_0 
  harfbuzz           conda-forge/linux-64::harfbuzz-9.0.0-hda332d3_1 
  hpack              conda-forge/noarch::hpack-4.0.0-pyh9f0ad1d_0 
  hyperframe         conda-forge/noarch::hyperframe-6.0.1-pyhd8ed1ab_0 
  icu                conda-forge/linux-64::icu-75.1-he02047a_0 
  idna               conda-forge/noarch::idna-3.10-pyhd8ed1ab_0 
  importlib_resourc~ conda-forge/noarch::importlib_resources-6.4.5-pyhd8ed1ab_0 
  jinja2             conda-forge/noarch::jinja2-3.1.4-pyhd8ed1ab_0 
  jsonpatch          conda-forge/noarch::jsonpatch-1.33-pyhd8ed1ab_0 
  jsonpointer        conda-forge/linux-64::jsonpointer-3.0.0-py39hf3d152e_1 
  jsonschema         conda-forge/noarch::jsonschema-4.23.0-pyhd8ed1ab_0 
  jsonschema-specif~ conda-forge/noarch::jsonschema-specifications-2023.12.1-pyhd8ed1ab_0 
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0 
  krb5               conda-forge/linux-64::krb5-1.21.3-h659f571_0 
  lame               conda-forge/linux-64::lame-3.100-h166bdaf_1003 
  libabseil          conda-forge/linux-64::libabseil-20240722.0-cxx17_h5888daf_1 
  libarchive         conda-forge/linux-64::libarchive-3.7.4-hfca40fe_0 
  libass             conda-forge/linux-64::libass-0.17.3-h1dc1e6a_0 
  libcurl            conda-forge/linux-64::libcurl-8.10.1-hbbe4b11_0 
  libdrm             conda-forge/linux-64::libdrm-2.4.123-hb9d3cd8_0 
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2 
  libev              conda-forge/linux-64::libev-4.33-hd590300_2 
  libexpat           conda-forge/linux-64::libexpat-2.6.3-h5888daf_0 
  libglib            conda-forge/linux-64::libglib-2.82.1-h2ff4ddf_0 
  libhwloc           conda-forge/linux-64::libhwloc-2.11.1-default_hecaa2ac_1000 
  libiconv           conda-forge/linux-64::libiconv-1.17-hd590300_2 
  liblief            conda-forge/linux-64::liblief-0.14.1-h5888daf_2 
  libmamba           conda-forge/linux-64::libmamba-1.5.10-hf72d635_1 
  libmambapy         conda-forge/linux-64::libmambapy-1.5.10-py39h7a57059_1 
  libnghttp2         conda-forge/linux-64::libnghttp2-1.58.0-h47da74e_1 
  libopenvino        conda-forge/linux-64::libopenvino-2024.4.0-hac27bb2_1 
  libopenvino-auto-~ conda-forge/linux-64::libopenvino-auto-batch-plugin-2024.4.0-h4d9b6c2_1 
  libopenvino-auto-~ conda-forge/linux-64::libopenvino-auto-plugin-2024.4.0-h4d9b6c2_1 
  libopenvino-heter~ conda-forge/linux-64::libopenvino-hetero-plugin-2024.4.0-h3f63f65_1 
  libopenvino-intel~ conda-forge/linux-64::libopenvino-intel-cpu-plugin-2024.4.0-hac27bb2_1 
  libopenvino-intel~ conda-forge/linux-64::libopenvino-intel-gpu-plugin-2024.4.0-hac27bb2_1 
  libopenvino-intel~ conda-forge/linux-64::libopenvino-intel-npu-plugin-2024.4.0-hac27bb2_1 
  libopenvino-ir-fr~ conda-forge/linux-64::libopenvino-ir-frontend-2024.4.0-h3f63f65_1 
  libopenvino-onnx-~ conda-forge/linux-64::libopenvino-onnx-frontend-2024.4.0-he882d9a_1 
  libopenvino-paddl~ conda-forge/linux-64::libopenvino-paddle-frontend-2024.4.0-he882d9a_1 
  libopenvino-pytor~ conda-forge/linux-64::libopenvino-pytorch-frontend-2024.4.0-h5888daf_1 
  libopenvino-tenso~ conda-forge/linux-64::libopenvino-tensorflow-frontend-2024.4.0-h9718a47_1 
  libopenvino-tenso~ conda-forge/linux-64::libopenvino-tensorflow-lite-frontend-2024.4.0-h5888daf_1 
  libopus            conda-forge/linux-64::libopus-1.3.1-h7f98852_1 
  libpciaccess       conda-forge/linux-64::libpciaccess-0.18-hd590300_0 
  libpng             conda-forge/linux-64::libpng-1.6.44-hadc24fc_0 
  libprotobuf        conda-forge/linux-64::libprotobuf-5.27.5-h5b01275_2 
  libsolv            conda-forge/linux-64::libsolv-0.7.30-h3509ff9_0 
  libssh2            conda-forge/linux-64::libssh2-1.11.0-h0841786_0 
  libstdcxx          conda-forge/linux-64::libstdcxx-14.1.0-hc0a3c3a_1 
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-14.1.0-h4852527_1 
  libva              conda-forge/linux-64::libva-2.22.0-hb711507_0 
  libvpx             conda-forge/linux-64::libvpx-1.14.1-hac33072_0 
  libxcb             conda-forge/linux-64::libxcb-1.16-hb9d3cd8_1 
  libxml2            conda-forge/linux-64::libxml2-2.12.7-he7c6b58_4 
  lz4-c              conda-forge/linux-64::lz4-c-1.9.4-hcb278e6_0 
  lzo                conda-forge/linux-64::lzo-2.10-hd590300_1001 
  markupsafe         conda-forge/linux-64::markupsafe-2.1.5-py39h8cd3c5a_1 
  menuinst           conda-forge/linux-64::menuinst-2.1.2-py39hf3d152e_1 
  more-itertools     conda-forge/noarch::more-itertools-10.5.0-pyhd8ed1ab_0 
  ocl-icd            conda-forge/linux-64::ocl-icd-2.3.2-hd590300_1 
  openh264           conda-forge/linux-64::openh264-2.4.1-h59595ed_0 
  packaging          conda-forge/noarch::packaging-24.1-pyhd8ed1ab_0 
  patch              conda-forge/linux-64::patch-2.7.6-h7f98852_1002 
  patchelf           conda-forge/linux-64::patchelf-0.17.2-h58526e2_0 
  pcre2              conda-forge/linux-64::pcre2-10.44-hba22ea6_2 
  pixman             conda-forge/linux-64::pixman-0.43.2-h59595ed_0 
  pkginfo            conda-forge/noarch::pkginfo-1.11.1-pyhd8ed1ab_0 
  pkgutil-resolve-n~ conda-forge/noarch::pkgutil-resolve-name-1.3.10-pyhd8ed1ab_1 
  platformdirs       conda-forge/noarch::platformdirs-4.3.6-pyhd8ed1ab_0 
  pluggy             conda-forge/noarch::pluggy-1.5.0-pyhd8ed1ab_0 
  psutil             conda-forge/linux-64::psutil-6.0.0-py39h8cd3c5a_1 
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-hb9d3cd8_1002 
  pugixml            conda-forge/linux-64::pugixml-1.14-h59595ed_0 
  py-lief            conda-forge/linux-64::py-lief-0.14.1-py39hf88036b_2 
  pybind11-abi       conda-forge/noarch::pybind11-abi-4-hd8ed1ab_3 
  pycosat            conda-forge/linux-64::pycosat-0.6.6-py39hd1e30aa_0 
  pycparser          conda-forge/noarch::pycparser-2.22-pyhd8ed1ab_0 
  pysocks            conda-forge/noarch::pysocks-1.7.1-pyha2e5f31_6 
  python-libarchive~ conda-forge/linux-64::python-libarchive-c-5.1-py39hf3d152e_1 
  python_abi         conda-forge/linux-64::python_abi-3.9-5_cp39 
  pytz               conda-forge/noarch::pytz-2024.2-pyhd8ed1ab_0 
  pyyaml             conda-forge/linux-64::pyyaml-6.0.2-py39h8cd3c5a_1 
  referencing        conda-forge/noarch::referencing-0.35.1-pyhd8ed1ab_0 
  reproc             conda-forge/linux-64::reproc-14.2.4.post0-hd590300_1 
  reproc-cpp         conda-forge/linux-64::reproc-cpp-14.2.4.post0-h59595ed_1 
  requests           conda-forge/noarch::requests-2.32.3-pyhd8ed1ab_0 
  ripgrep            conda-forge/linux-64::ripgrep-14.1.0-h8fae777_1 
  rpds-py            conda-forge/linux-64::rpds-py-0.20.0-py39he612d8f_1 
  ruamel.yaml        conda-forge/linux-64::ruamel.yaml-0.18.6-py39hd1e30aa_0 
  ruamel.yaml.clib   conda-forge/linux-64::ruamel.yaml.clib-0.2.8-py39hd1e30aa_0 
  snappy             conda-forge/linux-64::snappy-1.2.1-ha2e4443_0 
  soupsieve          conda-forge/noarch::soupsieve-2.5-pyhd8ed1ab_1 
  svt-av1            conda-forge/linux-64::svt-av1-2.2.1-h5888daf_0 
  tbb                conda-forge/linux-64::tbb-2021.13.0-h84d6215_0 
  tomli              conda-forge/noarch::tomli-2.0.2-pyhd8ed1ab_0 
  tqdm               conda-forge/noarch::tqdm-4.66.5-pyhd8ed1ab_0 
  urllib3            conda-forge/noarch::urllib3-2.2.3-pyhd8ed1ab_0 
  wayland            conda-forge/linux-64::wayland-1.23.1-h3e06ad9_0 
  wayland-protocols  conda-forge/noarch::wayland-protocols-1.37-hd8ed1ab_0 
  x264               conda-forge/linux-64::x264-1!164.3095-h166bdaf_2 
  x265               conda-forge/linux-64::x265-3.5-h924138e_3 
  xorg-fixesproto    conda-forge/linux-64::xorg-fixesproto-5.0-hb9d3cd8_1003 
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-hb9d3cd8_1003 
  xorg-libice        conda-forge/linux-64::xorg-libice-1.1.1-hb9d3cd8_1 
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.4-he73a12e_1 
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.8.9-hb711507_1 
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.11-hb9d3cd8_1 
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.5-hb9d3cd8_0 
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h0b41bf4_2 
  xorg-libxfixes     conda-forge/linux-64::xorg-libxfixes-5.0.3-h7f98852_1004 
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.11-hd590300_0 
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-hb9d3cd8_1003 
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-hb9d3cd8_1004 
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-hb9d3cd8_1008 
  yaml               conda-forge/linux-64::yaml-0.2.5-h7f98852_2 
  yaml-cpp           conda-forge/linux-64::yaml-cpp-0.8.0-h59595ed_0 
  zipp               conda-forge/noarch::zipp-3.20.2-pyhd8ed1ab_0 
  zlib               conda-forge/linux-64::zlib-1.3.1-hb9d3cd8_2 
  zstandard          conda-forge/linux-64::zstandard-0.23.0-py39h08a7858_1 
  zstd               conda-forge/linux-64::zstd-1.5.6-ha6fb4c9_0 



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Requirement already satisfied: pip in /root/.cache/nerfbaselines/conda-envs/gaussian-splatting/af2209beed259f3a45e0aaebd6c540019177739944aaf74ddc7791022ff83d4a/gaussian-splatting/lib/python3.9/site-packages (24.2)
Requirement already satisfied: setuptools in /root/.cache/nerfbaselines/conda-envs/gaussian-splatting/af2209beed259f3a45e0aaebd6c540019177739944aaf74ddc7791022ff83d4a/gaussian-splatting/lib/python3.9/site-packages (75.1.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Cloning into 'gaussian-splatting'...
remote: Enumerating objects: 808, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 808 (delta 3), reused 8 (delta 3), pack-reused 795 (from 1)
Receiving objects: 100% (808/808), 76.95 MiB | 24.63 MiB/s, done.
Resolving deltas: 100% (461/461), done.
Submodule 'SIBR_viewers' (https://gitlab.inria.fr/sibr/sibr_core.git) registered for path 'SIBR_viewers'
Submodule 'submodules/diff-gaussian-rasterization' (https://github.com/graphdeco-inria/diff-gaussian-rasterization) registered for path 'submodules/diff-gaussian-rasterization'
Submodule 'submodules/simple-knn' (https://gitlab.inria.fr/bkerbl/simple-knn.git) registered for path 'submodules/simple-knn'
Cloning into '/root/.cache/nerfbaselines/conda-envs/gaussian-splatting/af2209beed259f3a45e0aaebd6c540019177739944aaf74ddc7791022ff83d4a/gaussian-splatting/src/gaussian-splatting/SIBR_viewers'...
remote: Enumerating objects: 3263, done.        
remote: Counting objects: 100% (317/317), done.        
remote: Compressing objects: 100% (170/170), done.        
remote: Total 3263 (delta 166), reused 271 (delta 147), pack-reused 2946 (from 1)        
Receiving objects: 100% (3263/3263), 9.98 MiB | 42.04 MiB/s, done.
Resolving deltas: 100% (2009/2009), done.
Cloning into '/root/.cache/nerfbaselines/conda-envs/gaussian-splatting/af2209beed259f3a45e0aaebd6c540019177739944aaf74ddc7791022ff83d4a/gaussian-splatting/src/gaussian-splatting/submodules/diff-gaussian-rasterization'...
remote: Enumerating objects: 263, done.        
remote: Counting objects: 100% (41/41), done.        
remote: Compressing objects: 100% (25/25), done.        
remote: Total 263 (delta 23), reused 22 (delta 13), pack-reused 222 (from 1)        
Receiving objects: 100% (263/263), 101.61 KiB | 5.98 MiB/s, done.
Resolving deltas: 100% (162/162), done.
Cloning into '/root/.cache/nerfbaselines/conda-envs/gaussian-splatting/af2209beed259f3a45e0aaebd6c540019177739944aaf74ddc7791022ff83d4a/gaussian-splatting/src/gaussian-splatting/submodules/simple-knn'...
remote: Enumerating objects: 37, done.        
remote: Counting objects: 100% (37/37), done.        
remote: Compressing objects: 100% (34/34), done.        
remote: Total 37 (delta 18), reused 0 (delta 0), pack-reused 0 (from 0)        
Submodule path 'SIBR_viewers': checked out '212f9fbb59d88db0022cd1326a8458759bf310ad'
Submodule path 'submodules/diff-gaussian-rasterization': checked out '59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d'
Submodule 'third_party/glm' (https://github.com/g-truc/glm.git) registered for path 'submodules/diff-gaussian-rasterization/third_party/glm'
Cloning into '/root/.cache/nerfbaselines/conda-envs/gaussian-splatting/af2209beed259f3a45e0aaebd6c540019177739944aaf74ddc7791022ff83d4a/gaussian-splatting/src/gaussian-splatting/submodules/diff-gaussian-rasterization/third_party/glm'...
remote: Enumerating objects: 59615, done.        
remote: Counting objects: 100% (5/5), done.        
remote: Compressing objects: 100% (4/4), done.        
remote: Total 59615 (delta 0), reused 3 (delta 0), pack-reused 59610 (from 1)        
Receiving objects: 100% (59615/59615), 71.20 MiB | 20.65 MiB/s, done.
Resolving deltas: 100% (45209/45209), done.
Submodule path 'submodules/diff-gaussian-rasterization/third_party/glm': checked out '5c46b9c07008ae65cb81ab79cd677ecc1934b903'
Submodule path 'submodules/simple-knn': checked out '86710c2d4b46680c02301765dd79e465819c8f19'
M       SIBR_viewers
M       submodules/simple-knn
Note: switching to '2eee0e26d2d5fd00ec462df47752223952f6bf4e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 2eee0e2 Bumped sibr viewers
Collecting package metadata (current_repodata.json): - WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): | WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
done
Solving environment: - `

**Comment by jkulhanek** [comment]
Take a look at nerfbaselines' documentation. There is env variable "NERFBASELINES_PREFIX" which will change the location of the cache directory. As for solving environment, I'm afraid it can just take longer. I would recommend following the nerfbaselines install instructions and install miniforge which should be faster.

**Comment by jkulhanek** [comment]
From my understanding the issue is now resolved? Please reopen if not.

**Comment by Joaquin-Gajardo** [comment]
all good thanks a lot!
