### ISSUE TITLE
Is there any specific reasons on using readme command as cloning method?  

### ISSUE THREAD

**Issue by CultureAddiction** [jkulhanek/wild-gaussians#29]
In readme, you have suggested "git clone git@github.com:jkulhanek/wild-gaussians.git" command as cloning repository, but i experienced this error on following given command. 

![image](https://github.com/user-attachments/assets/2129e97c-740a-416a-bec6-f5c2dbe1d927)

Instead, I used common cloning command "https://github.com/jkulhanek/wild-gaussians.git".
There was no error with this command on cloning. This... this choice will not cause any problems in the future, or will it? 

I'm just curious about if you had any specific reasons on using such command. Please let me know. 

Thank you.

**Comment by jkulhanek** [comment]
Hi, thanks for the suggestion. I updated the READMe with your suggested URL instead of SSH to make it easier to clone the repo for people who did not setup SSH.
