### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '[N/A]'

### ISSUE THREAD

**Issue by az396** [jkulhanek/wild-gaussians#4]
Hello,
I am encountering an issue while trying to run the train.py script from the WildGaussians project. When I directly run the script in the wildgaussian directory, I receive the following error:
![0673901bae69b50ce34d7cb6b380bd3](https://github.com/user-attachments/assets/62390857-f06d-4efb-9fbf-95e330bdf802)

The error seems to be related to obtaining memory utilization information during the training process. It appears that the script is trying to access system resources and retrieve memory usage, but encounters an error when trying to convert a string '[N/A]' to an integer.
I have tried running the script both with and without the nerfbaselines command-line tool, but the issue persists. I suspect that there might be a problem with retrieving memory utilization information or a compatibility issue with the system's resource tools.
Could you please provide guidance on how to resolve this issue? Any help would be greatly appreciated.
Thank you!

**Comment by jkulhanek** [comment]
Thanks for reporting. I don’t know why this happens for you. I will send a fix. In the meantime, can you please disable the core retrieving system resources utilisation? It is not needed.

**Comment by az396** [comment]
Thank you for your prompt reply and for offering a fix.

In the meantime, I will disable the core retrieving system resources utilization as you suggested. Thank you for the guidance.

Additionally, I would like to know how to directly use train.py for training instead of invoking it through the library. This would make it easier for me to modify the code. I appreciate your response.

**Comment by jkulhanek** [comment]
You can use ‘python -m wildgaussians.train’ with the rest of the arguments being the same as for nerfbaselines (but without —method)

**Comment by az396** [comment]
thank you for explaining how to directly use train.py for training. I will follow your instructions and use python -m wildgaussians.train with the same arguments as for nerfbaselines, but without --method.
I appreciate your assistance.

**Comment by jkulhanek** [comment]
Hi, can you please give me details on your system? Which system (and which version), which version of `ps` you have and if/how you installed cuda? Thanks!

**Comment by jkulhanek** [comment]
Btw, the error occurs only if you train through nerfbaselines. Using train.py directly should work. See that the source of the error is logging resource util in nerfbaselines code. I patched the code in nerfbaselines (resource util is not logged for windows now). If you want to run it, please install the newest version from main. But I still don't know if the code will work on windows.

**Comment by az396** [comment]
Thank you for your prompt response and for providing a solution to the error I encountered. I appreciate your suggestion of using train.py directly instead of nerfbaselines, and I will definitely give it a try. Additionally, I'm glad to inform you that I have successfully run the code on Ubuntu.I also appreciate your effort in patching the code in nerfbaselines to address the logging of resource util for Windows. I will install the latest version from the main repository and attempt to run the code using train.py. Should I encounter any issues or have further questions, I hope I can reach out to you for assistance.Once again, I want to express my gratitude for taking the time to respond to my query. Your guidance has been invaluable in overcoming this hurdle.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jkulhanek/wild-gaussians"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月23日(星期二) 晚上7:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jkulhanek/wild-gaussians] ValueError: invalid literal for int() with base 10: '[N/A]' (Issue #4)





 
Btw, the error occurs only if you train through nerfbaselines. Using train.py directly should work. See that the source of the error is logging resource util in nerfbaselines code. I patched the code in nerfbaselines (resource util is not logged for windows now). If you want to run it, please install the newest version from main. But I still don't know if the code will work on windows.

**Comment by az396** [comment]
I hope this email finds you well. I wanted to inform you that I have successfully trained my model using the command&nbsp;python -m&nbsp;and obtained the desired results. However, I encountered a challenge when trying to view the training results.

It seems that using&nbsp;nerfbaselines viewer&nbsp;does not generate the required&nbsp;nb-info.json&nbsp;file, leading to limited output results. I would like to explore alternative options for viewing the training results. Specifically, I am interested in utilizing the 3dgs viewer to visualize the results.

Could you please provide guidance on how to use the 3dgs viewer to view the results of the trained model? Alternatively, if there is any other recommended method or tool for viewing the results, I would greatly appreciate your advice and insights.

Thank you very much for your time and support. I look forward to your response.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jkulhanek/wild-gaussians"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月23日(星期二) 晚上7:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jkulhanek/wild-gaussians] ValueError: invalid literal for int() with base 10: '[N/A]' (Issue #4)





 
Closed #4 as completed.
