### ISSUE TITLE
Questions about preprocessing the data

### ISSUE THREAD

**Issue by fyhdev** [jkulhanek/wild-gaussians#5]
Hi, nice work! Really impressed by it. However, I still got some questions:
 a) When I download the Nerf-on-go dataset(eg:fountain), I get three files: checkpoints,predictions and tensorboards. Could you explain the meaning of each file?
 b) In the rendering process, it is said that we need the checkpoints and the trajectory. So is this checkpoint from the training output and the trajectory from the interactive viewer? If so, how can I export the trajectory as a file in my repository after I can visualizing the interactive viewer in the viser?
 c) In the training process, if I want to train based on the Nerf-on-go dataset, where is the data path. Is the data path the path of checkpoints, predictions or tensorboards?
These are several questions confusing me. I will be really grateful if you could answer my questions!

**Comment by jkulhanek** [comment]
Hi,
a) Where did you download it from? What you are describing are the trained checkpoints, not the datasets. Perhaps you downloaded the checkpoints instead of the dataset? The dataset should be here: https://huggingface.co/datasets/jkulhanek/nerfonthego-wg/tree/main
b) You are correct. If you open the viewer, in the render tab you can create the trajectory and by pressing the 'export trajectory' button you save the trajectory as a file.
c) Please follow the link to the data in the README. The data is hosted on huggingface. It is different from the data path of checkpoint/predictions/tensorboard.

Best,
Jonas

**Comment by fyhdev** [comment]
Thanks for you reply! It helps me a lot. But now I found a new problem that when I am rendering a video, my terminal said that "nerfbaselines render has no such option --trajectory". Is it because my nerfbaselines=1.01 and I should have a greater version of it?

**Comment by jkulhanek** [comment]
I see, please use the ‘nerfbaselines render-trajectory’ command for your version

**Comment by fyhdev** [comment]
Thanks, so checkpoints, predictions and tensorboards are results trained from the images right? By the way, get another problem in rendering the video.
![Screenshot 2024-07-27 113804](https://github.com/user-attachments/assets/bb521f08-bccc-4c30-ae24-609aca82bbfa)
This is the screenshot of my error. It is said that need at least one array to stack. Can't figure out why?

**Comment by jkulhanek** [comment]
Please always attach full command and full traceback of the error

**Comment by fyhdev** [comment]
Got it. Sorry for that. This is the screenshot of my whole error. It seems like an error caused by my environment.
![Uploading Screenshot 2024-07-27 131503.png…]()

**Comment by fyhdev** [comment]
![Screenshot 2024-07-27 131503](https://github.com/user-attachments/assets/ba383806-60a8-4409-9e62-f9eedaa082c1)

**Comment by jkulhanek** [comment]
Can you please also share the trajectory file? Seems like you have 0 frames in your trajectory? Did you add at least two keyframes to the trajectory in the viewer?

**Comment by fyhdev** [comment]
Yes, you are right. I didn't add keyframes. How can I render a video by the way? Using the command you gave me 'nerfbaselines render-trajectory’, I can only get several images on a single view. How can I get a video on a 360 view? Thanks for your reply!

**Comment by jkulhanek** [comment]
When you play the trajectory in the viewer it is a video or does it jump between keyfranes? Perhaps you change the interpolation type to none under render setting in the viewer. Also note, you can render the trajectory directly from the viewer, no need to run the render-trajectory command

**Comment by fyhdev** [comment]
I see. It jumps between keyframes. I did find a render  button in the viewer. However, there will be an error when I press that button.
![Screenshot 2024-07-31 001206](https://github.com/user-attachments/assets/85252afa-896c-41ff-b653-76bb50774387)

**Comment by fyhdev** [comment]
Also, the type of my interpolation is kochanek-bartels. Is it ok?

**Comment by jkulhanek** [comment]
Kochanek-bartels is ok. Can you share the trajectory.json file?

**Comment by fyhdev** [comment]
[trajectory-NEW.json](https://github.com/user-attachments/files/16443303/trajectory-NEW.json)
This is my trajectory file

**Comment by fyhdev** [comment]
Also, where can I get the original image on the photo tourism dataset. I can only get the trained data from your link.

**Comment by jkulhanek** [comment]
Your trajectory contains several keyframes with a single camera view. You have to add a key frame, move the camera somewhere, add new keyframe, etc... to build a trajectory. Also, the reason ffmpeg is not working for you is probably an old version of ffmpeg not matching your mediapy version. Perhaps try updating ffmpeg.

**Comment by abenbihi** [comment]
Hi,

Thanks for releasing the code and the documentation.
I am running the code on a custom COLMAP dataset

On rendering new trajectories, it seems that the `render-trajectory` command of `nerfbaselines` expect the checkpoint folder to hold a file `nb-info.json` with information on the background and the expected scene scale, which I assume should be generated by the code.
However, there is no such folder in the checkpoint directory.

Any idea what may be going on here?

I am running the latest version of the main branch of wild-gaussians with `nerbaselines==1.0.2`

Below is the stack trace

Thanks

```
info: Loading checkpoint checkpoint-70000/
Traceback (most recent call last):
  File "conda/envs/wg/bin/nerfbaselines", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "conda/envs/wg/lib/python3.11/site-packages/click/core.py", line 1157, in __call__                                                                                                
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "conda/envs/wg/lib/python3.11/site-packages/click/core.py", line 1078, in main                                                                                                    
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "conda/envs/wg/lib/python3.11/site-packages/click/core.py", line 1688, in invoke                                                                                                  
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "conda/envs/wg/lib/python3.11/site-packages/click/core.py", line 1434, in invoke                                                                                                  
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "conda/envs/wg/lib/python3.11/site-packages/click/core.py", line 783, in invoke                                                                                                   
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "conda/envs/wg/lib/python3.11/site-packages/nerfbaselines/utils.py", line 341, in wrapped                                                                                         
    raise e
  File "conda/envs/wg/lib/python3.11/site-packages/nerfbaselines/utils.py", line 334, in wrapped                                                                                         
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "conda/envs/wg/lib/python3.11/site-packages/nerfbaselines/cli/render.py", line 120, in render_trajectory_command                                                                  
    assert (checkpoint_path / "nb-info.json").exists(), f"checkpoint path {checkpoint} does not contain nb-info.json"                                                                                             
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: checkpoint path checkpoint-70000/ does not contain nb-info.json
```

**Comment by jkulhanek** [comment]
Sorry for the issue, I'm currently working on an update that should fix the issue. I assume you train the model using the train.py script, not `nerfbaselines train`, but now you want to use the checkpoint with `nerfbaselines *` command is that correct? In that case, can you just add an `nb-info.json` file to the checkpoint directory with the following contents: `{"method": "wild-gaussians"}`? Does it (temporarily) resolve the issue?

**Comment by abenbihi** [comment]
No worries and thanks for the quick reply!

Yes, manually adding the `nb-info.json` solves the issue.

Indeed, I trained the model using the `wild-gaussians` `train.py` and wanted to then render views from the trained model.
The documentation suggested to use `nerfbaselines` for rendering but if there is a `wild-gaussian` rendering script that is independent of `nerfbaselines`, that would work too.

**Comment by jkulhanek** [comment]
This should now be resolved: the train.py script will generate nb-info.json

**Comment by juliantang324** [comment]
> It's great that we can render a video given the trajectory. But how do I change the appearance of the scene as I move through the trajectory? Is there a way to do that?

To dynamically change the scene appearance along your camera trajectory, modify your `trajectory.json` by adding an `"appearances"` array with `"embedding_train_index"` values for each keyframe. Here's how:  

1. **Add the `appearances` key** to your trajectory configuration:
   ```json
   "appearances": [
     {
       "embedding_train_index": 0    // Appearance at keyframe 0
     },
     {
       "embedding_train_index": 1    // Appearance at keyframe 1
     },
     {
       "embedding_train_index": 2    // Appearance at keyframe 2
     },
   ]
   ```

2. **Key Details**:
   - Each entry corresponds to a keyframe in your trajectory, in sequential order.
   - The `embedding_train_index` refers to pre-trained appearance embeddings (from your training checkpoints).
   - The renderer will smoothly interpolate appearances between these indices along the trajectory.
