### ISSUE TITLE
A dynamic point question

### ISSUE THREAD

**Issue by WuJH2001** [jkulhanek/wild-gaussians#6]
Very enlightening work. I have a question I would like to ask. Does the Gaussian point used to render transient objects in the scene always exist and is only rendered at a specific moment? If this is the case, will it cause the number of points to be too large?

**Comment by jkulhanek** [comment]
Hi, there are no transient Gaussians. All Gaussians are always visible every time.  The masking is used to mask you 2D regions in the GT images in order to ignore these transient objects.
