### ISSUE TITLE
How to specify image resolution size

### ISSUE THREAD

**Issue by santolina** [jkulhanek/wild-gaussians#8]
Thank you very much for your great work.

BTW, Is there any parameter to explicitly specify image resolution like "--resolution 1920" in vanilla GS ?

**Comment by jkulhanek** [comment]
Hi, sorry, but at the moment there is no argument to specify the image resolution. You can copy a dataset and add an `nb-info.json` file with a custom downscale factor. Would this resolve your issue?

**Comment by yuzewang1998** [comment]
Hi, could you please give more information about how to add such `nb-info.json` and use it? I can't find such config file in the code of Wild-Gaussians or NerfBaselines.

**Comment by jkulhanek** [comment]
Can you please take a look at the released NeRF on-the-go dataset? Each scene should contain `nb-info.json` so you can take a look at how it is defined. It basically defines the dataset's metadata. By setting `downscale_loaded_factor=2` the images will be automatically downscaled by a factor of 2 on loading. Take a look at the relevant code: https://github.com/jkulhanek/nerfbaselines/blob/72a3aa8c55bca9fe190d76645fd7db710250661e/nerfbaselines/datasets/_common.py#L247C39-L247C62

**Comment by yuzewang1998** [comment]
Thank you very much for your patience in explaining. I started to download only the PT dataset, so I didn't see the nb-info.json, I'm very sorry.

**Comment by jkulhanek** [comment]
Please take a look at the documentation https://jkulhanek.com/nerfbaselines/docs/using-custom-data.html
